kind: pipeline
name: test-ci
type: docker

steps:
  - name: docker
    image: plugins/docker
    settings:
      registry: core-harbor.my.com:30443
      repo: core-harbor.my.com:30443/test-ci/one
      no_cache: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
