[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "16"

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run vite-ssg build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
